### ISSUE TITLE
[FEATURE] (Replay) Implementar Request de Dados o Replay

### ISSUE THREAD

**Issue by rummenigged** [moraisnetocc/setupTVTest#11]
Implementar request de lista de canais do replay com a lista de programas disponíveis para serem assistidos

- [x] Request de Dados

- [x] Envio Para a View

**Comment by moraisnetocc** [comment]
"data": [
        {
            "categories": "[\"Histórico\"]",
            "contributors": "{\"actors\":[],\"directors\":[]}",
            "data_inicio_formatada": "02/21/2019 08:20:00",
            "data_parada_formatada": "02/21/2019 09:10:00",
            "description": "Os pântanos dos Estados Unidos são um grande deserto, constituído de milhares de hectares, que possuem suas próprias regras. Ali a sobrevivência depende de inteligência, ciência, coragem, trabalho árduo e uma abordagem única. Neste programa vamos conhecer um barco construído para navegar nestas águas aparentemente intransitáveis, um projeto de engenharia ambicioso para tentar desviar o Rio Mississipi e ainda ficar cara a cara com cobras enormes e jacarés ameaçadores.",
            "endDate": "1550751000000",
            "genres": "Séries",
            "id": 96742751,
            "logo": 1,
            "name": "Maravilhas Modernas",
            "parental_rating": 8,
            "program_id": "31184",
            "replay_uri": "http://replay-01.iptv.brisanet.net.br:1935/dvredge/ip91.stream/playlist.m3u8?DVR&wowzadvrplayliststart=20190221082000&wowzadvrplaylistduration=3000000",
            "startDate": "1550748000000",
            "sub_titulo": "A Tecnologia dos Pântanos Temp. 18 Ep. 3"
        },
        {
            "categories": "[\"Histórico\"]",
            "contributors": "{\"actors\":[],\"directors\":[\"George Pagliero\"]}",
            "data_inicio_formatada": "02/21/2019 07:35:00",
            "data_parada_formatada": "02/21/2019 08:20:00",
            "description": "Conheça o sistema de refúgios subterrâneos, que contava inclusive com câmeras de segurança, construído pelos ingleses durante a Segunda Guerra Mundial para proteger o Primeiro Ministro Winston Churchill.",
            "endDate": "1550748000000",
            "genres": "Séries",
            "id": 96742750,
            "logo": 1,
            "name": "Mundos Perdidos",
            "parental_rating": 10,
            "program_id": "74085",
            "replay_uri": "http://replay-01.iptv.brisanet.net.br:1935/dvredge/ip91.stream/playlist.m3u8?DVR&wowzadvrplayliststart=20190221073500&wowzadvrplaylistduration=2700000",
            "startDate": "1550745300000",
            "sub_titulo": "Os Bunkers Secretos de Churchill Temp. 1 Ep. 9"
        },

request

**Comment by moraisnetocc** [comment]
foi implementado junto da outra issue
