### ISSUE TITLE
[FEATURE] (Guide) Request de Detalhe do Programa

### ISSUE THREAD

**Issue by moraisnetocc** [moraisnetocc/setupTVTest#32]
Implementar request de captura de detalhes de programa junto com as requestes de canais e programas. Persistir dados capturados como um só modelo de banco. Detalhe do programa deve ser um atributo do programa e programa é um atributo do canal.

**Comment by rummenigged** [comment]
Problema ao tentar pegar detalhes de um programa impede que a lista de canais seja enviada para o usu case de player e o stream não é iniciado
![screenshot from 2018-12-13 12-53-45](https://user-images.githubusercontent.com/13321916/49950813-48f15780-fed7-11e8-845f-645dafa1aaf3.png)
